/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;


import DAO.Conexao;
import DAO.DisciplinaDAO;
import DAO.CursoDAO;
import DTO.Disciplina;
import DTO.Curso;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class DisciplinaVIEW extends javax.swing.JFrame {

    /**
     * Creates new form DisciplinaVIEW
     */
    public DisciplinaVIEW() {
        initComponents();
        ListarValores();
        ListarValoresCurso();
        restaurarDadoscmcCurso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        cmbCurso = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCurso = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtId_disciplina = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        txtPesquisarNomeAluno = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        txtPesquisarNomeCurso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisciplina = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCarregarCampos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema Escola - Disciplinas");
        setResizable(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("DISCIPLINA");

        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));
        cmbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCursoActionPerformed(evt);
            }
        });

        tblCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id_curso", "Nome"
            }
        ));
        tblCurso.setEnabled(false);
        tblCurso.setFocusable(false);
        jScrollPane2.setViewportView(tblCurso);

        jLabel3.setText("ID");

        txtId_disciplina.setEnabled(false);

        btnLimpar.setText("  Limpar Campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        txtPesquisarNomeAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarNomeAlunoKeyReleased(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/16x16.png"))); // NOI18N

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtPesquisarNomeCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarNomeCursoKeyReleased(evt);
            }
        });

        tblDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Id_Curso"
            }
        ));
        tblDisciplina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblDisciplinaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblDisciplina);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/16x16.png"))); // NOI18N

        jLabel7.setText("Pesquisar Curso:");

        btnCarregarCampos.setText("Carregar Campos");
        btnCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCamposActionPerformed(evt);
            }
        });

        jLabel8.setText("Pesquisar Disciplina:");

        jLabel4.setText("ID_Curso");

        jLabel1.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisarNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCarregarCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtNome)
                                                .addComponent(txtId_disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel9)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPesquisarNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtId_disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterar)
                            .addComponent(btnCadastrar)
                            .addComponent(btnExcluir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPesquisarNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9))
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCarregarCampos)
                        .addComponent(btnLimpar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPesquisarNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)))
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        LimparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Cadastrar();
        LimparCampos();
        ListarValores();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtPesquisarNomeAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarNomeAlunoKeyReleased
        // TODO add your handling code here:
        Pesquisar_Disciplina();
    }//GEN-LAST:event_txtPesquisarNomeAlunoKeyReleased

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        Alterar();
        ListarValores();
        LimparCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        Excluir();
        ListarValores();
        LimparCampos();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtPesquisarNomeCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarNomeCursoKeyReleased
        // TODO add your handling code here:
        Pesquisar_Curso();
    }//GEN-LAST:event_txtPesquisarNomeCursoKeyReleased

    private void tblDisciplinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDisciplinaKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tblDisciplinaKeyReleased

    private void btnCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCamposActionPerformed
        // TODO add your handling code here:
        CarregarCampos();
    }//GEN-LAST:event_btnCarregarCamposActionPerformed

    private void cmbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisciplinaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisciplinaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisciplinaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisciplinaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisciplinaVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCarregarCampos;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCurso;
    private javax.swing.JTable tblDisciplina;
    private javax.swing.JTextField txtId_disciplina;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisarNomeAluno;
    private javax.swing.JTextField txtPesquisarNomeCurso;
    // End of variables declaration//GEN-END:variables
private void ListarValores() {

        try {
            DisciplinaDAO objdisciplinadao = new DisciplinaDAO();

            DefaultTableModel model = (DefaultTableModel) tblDisciplina.getModel();
            model.setNumRows(0);

            ArrayList<Disciplina> lista = objdisciplinadao.PesquisarDisciplina();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_disciplina(),
                    lista.get(num).getNome_disciplina(),
                    lista.get(num).getId_curso(),});
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar valores DisciplinaVIEW" + erro);
        }
    }

    private void ListarValoresCurso() {
        try {

            CursoDAO objcursodao = new CursoDAO();
            DefaultTableModel model = (DefaultTableModel) tblCurso.getModel();
            model.setNumRows(0);

            ArrayList<Curso> lista = objcursodao.PesquisarCurso();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_curso(),
                    lista.get(num).getNome_curso(),});
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar valores DisciplinaVIEW" + erro);
        }
    }

    private void Pesquisar_Disciplina() {
    String sql = "select * from diciplina where nome_disciplina like ?";
    Connection conn;
    PreparedStatement pstm;
    ResultSet  rs;
        conn = new Conexao().conectaBD();
        try {
            pstm = conn.prepareStatement(sql);
            pstm.setString(1, txtPesquisarNomeAluno.getText() + "%");
            rs=pstm.executeQuery();
            
            tblDisciplina.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception erro) {
        JOptionPane.showMessageDialog(null, "Listar valores AlunoVIEW" + erro);
        }
    }
    
    private void Pesquisar_Curso(){
    String sql = "select * from curso where nome_curso like ?";
    Connection conn;
    PreparedStatement pstm;
    ResultSet  rs;
        conn = new Conexao().conectaBD();
          try {
            pstm = conn.prepareStatement(sql);
            pstm.setString(1, txtPesquisarNomeCurso.getText() + "%");
            rs=pstm.executeQuery();
            
            tblCurso.setModel(DbUtils.resultSetToTableModel(rs));
          } catch (Exception erro) {
              JOptionPane.showMessageDialog(null, "Listar valores AlunoVIEW" + erro);
          }
    }

    private void CarregarCampos() {
        int setar = tblDisciplina.getSelectedRow();

        txtId_disciplina.setText(tblDisciplina.getModel().getValueAt(setar, 0).toString());
        txtNome.setText(tblDisciplina.getModel().getValueAt(setar, 1).toString());
        cmbCurso.setSelectedItem(tblDisciplina.getModel().getValueAt(setar, 2).toString());

    }

    private void Cadastrar() {
        String nome_disciplina;
        int id_curso;

        nome_disciplina = txtNome.getText();
        id_curso = codcurso.get(cmbCurso.getSelectedIndex() - 1);

        Disciplina objdisciplina = new Disciplina();
        objdisciplina.setNome_disciplina(nome_disciplina);
        objdisciplina.setId_curso(id_curso);

        DisciplinaDAO objdisciplinadao = new DisciplinaDAO();
        objdisciplinadao.cadastrarDisciplina(objdisciplina);
        JOptionPane.showMessageDialog(null, "Cadastro Realizado");
    }

    private void LimparCampos() {
        txtId_disciplina.setText("");
        txtNome.setText("");
        cmbCurso.setSelectedIndex(0);
    }

    private void Alterar() {
        int id_disciplina, id_curso;
        String nome_disciplina;

        id_disciplina = Integer.parseInt(txtId_disciplina.getText());
        nome_disciplina = txtNome.getText();
        id_curso = codcurso.get(cmbCurso.getSelectedIndex() - 1);

        Disciplina objdisciplina = new Disciplina();
        objdisciplina.setId_disciplina(id_disciplina);
        objdisciplina.setNome_disciplina(nome_disciplina);
        objdisciplina.setId_curso(id_curso);

       DisciplinaDAO objdisciplinadao = new DisciplinaDAO();
        objdisciplinadao.AlterarDisciplina(objdisciplina);

    }

    private void Excluir() {

        int id_disciplina = Integer.parseInt(txtId_disciplina.getText());

        Disciplina objdisciplina = new Disciplina();
        objdisciplina.setId_disciplina(id_disciplina);

        DisciplinaDAO objdisciplinadao = new DisciplinaDAO();
        objdisciplinadao.ExcluirDisciplina(objdisciplina);
    }

    Vector<Integer> codcurso = new Vector<Integer>();

    public void restaurarDadoscmcCurso() {

        try {
            DisciplinaDAO objdisciplinadao = new DisciplinaDAO();
            ResultSet rs = objdisciplinadao.listarCurso();

            while (rs.next()) {
                codcurso.addElement(rs.getInt(1));
                cmbCurso.addItem(rs.getString(1));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "");
        }

    }
}
